### ISSUE TITLE
Don't list consecutive Edits

### ISSUE THREAD

**Issue by phischdev** [kulttuuri/slack_mediawiki#3] opened 2016-05-14 11:56 UTC
Idea: Option not to list minor updates and to list consecutive updates on the same article only once.

**Comment by kulttuuri** [comment] 2016-05-30 07:22
Configuration option not to list minor updates is easy to implement. Not to list consecutive updates probably would need database access so bit more tweaking. I'll take a look at this once I have some free time on my hands. :)

**Comment by kulttuuri** [comment] 2016-06-05 14:15
Added new optional command not to list minor updates:
// If this is true, all minor edits made to articles will not be submitted to Slack.
$wgSlackIgnoreMinorEdits = false;

**Comment by phischdev** [comment] 2016-07-25 20:26
Hey,
Sorry for my really late response. Thank you very much for your effort.
Not to list censucitve updates might be easy, if the last edited sites were just cached in a dictionary in memory. 
if not (site, user) in edited post() else if now() - edited[(site, user)] > 1h post()
and delete the oldest if the list exceed a limit or somehow like that :)

Thanks and regards
Philipp

Date: Mon, 30 May 2016 00:22:01 -0700

**Comment by kulttuuri** [comment] 2016-09-10 14:00
Alright, reopening this. Here's how I would think this would work: this could work so that for ex. each user can push notification to slack only once every 15 minutes. Once 15 minutes has passed and if there we're any new commits in between that time made into the system by that user, could add some infotext in slack attachment which shows how many edits we're made in between that time and some way to see them (I don't know if there is way to expand / collapse message in slack?)

**Comment by Meneth** [comment] 2016-09-10 16:03
Tricky part is telling what revisions have caused notifications. That'd probably need its own database table or something like that to keep track of it.
Tricky too to have it push a notification once the 15 minute period is up, seeing as it then needs some sort of scheduling ability.

So not entirely sure if it is workable.

**Comment by kulttuuri** [comment] 2016-09-14 17:50
Yeah, this seems like it would be pretty hard to implement.

**Comment by phischdev** [comment] 2016-09-15 08:28
So how about just remembering the (last user, last article) that pushed a notification?
Because this is the main source of spam in our Slack-Channel, when someone saves after each word.

**Comment by Meneth** [comment] 2016-09-15 08:47
Suppressing it isn't all that tricky. The problem is figuring out when to show it.
If the user is doing an edit every 5 minutes for 5 hours, if you just suppress it you'd only get a single alert at the start. Probably not what you'd want.

**Comment by kulttuuri** [comment] 2016-09-16 08:54
Could this be of any help? https://www.mediawiki.org/wiki/Manual:Job_queue

**Comment by Meneth** [comment] 2016-09-16 09:31
I'm not sure the job queue is really suited for that. For one, depending on how someone has their MW setup, it can vary wildly how often it is run.
There'd probably be significant overhead in creating and recreating the job until it is time to notify.
And if someone edits a significant template, then the job ending up at the end of the queue might mean it'll take quite some time for it to actually be run.

**Comment by kulttuuri** [comment] 2016-09-16 10:16
Yeah, that's what I though myself too. Running automated tasks might not work on some environments and work weirdly on some. I don't currently have other ideas for this feature to work well. Others? :)

**Comment by kulttuuri** [comment] 2016-11-24 13:37
Closing.

**Closed by kulttuuri** 2016-11-24 13:37 UTC
