### ISSUE TITLE
Notifications configuration

### ISSUE THREAD

**Issue by dedvardsson** [kulttuuri/slack_mediawiki#2] opened 2016-03-01 18:42 UTC
Hi,
First of all thanks for a great extension. 
I´m having some issues to use the configuration of the notifications. 
I have set everything to false except "AddedArticle" but it´s still posting changes, removals etc, and added the settings in the bottom of LocalSettings.php
Dose anyone have any idea abot what might be the issue?

$wgSlackNotificationNewUser = false;
$wgSlackNotificationBlockedUser = false;
$wgSlackNotificationAddedArticle = true;
$wgSlackNotificationRemovedArticle = false;
$wgSlackNotificationMovedArticle = false;
$wgSlackNotificationEditedArticle = false;
$wgSlackNotificationFileUpload = false;

Thanks

**Comment by kulttuuri** [comment] 2016-03-01 21:04
I'll try to take a look at this tomorrow :)

**Comment by dedvardsson** [comment] 2016-03-01 21:54
Ok, thank you :)
Let me know if you need any more info.

**Comment by dedvardsson** [comment] 2016-03-04 11:06
Hi kulttuuri,
Did you manage to have a look on this?

**Comment by kulttuuri** [comment] 2016-03-04 12:17
Can you try setting these settings before calling the require_once("$IP/extensions/SlackNotifications/slack_notifications.php"); and let me know if that works?

**Comment by dedvardsson** [comment] 2016-03-05 01:11
Hi, 

Thanks for your reply. 
I have actually already added the require_once statement in my LocalSettings.php.
The extension works, but the configuration of the notifications dosent seem to work. 

I have added my settings in LocalSettings.php below.


require_once "$IP/extensions/SlackNotifications/slack_notifications.php";

#SlackIntegration
$wgSlackIncomingWebhookUrl = "https://hooks.slack.com/services/XXXXX/XXXXXXXXXXXXXXXXXXXXXXX";
$wgSlackFromName = "Wiki";
$wgWikiUrl = "http://192.168.60.130";
$wgWikiUrlEnding = "/index.php/";
$wgSlackSendMethod = "curl";
$wgSlackNotificationNewUser = "false";
$wgSlackNotificationBlockedUser = "false";
$wgSlackNotificationAddedArticle = "true";
$wgSlackNotificationRemovedArticle = "false";
$wgSlackNotificationMovedArticle = "false";
$wgSlackNotificationEditedArticle = "false";
$wgSlackNotificationFileUpload = "false";

I also tried: 
require_once "$IP/extensions/SlackNotifications/slack_notifications.php";

#SlackIntegration
$wgSlackIncomingWebhookUrl = "https://hooks.slack.com/services/XXXXX/XXXXXXXXXXXXXXXXXXXXXXX";
$wgSlackFromName = "Wiki";
$wgWikiUrl = "http://192.168.60.130";
$wgWikiUrlEnding = "/index.php/";
$wgSlackSendMethod = "curl";
$wgSlackNotificationNewUser = false;
$wgSlackNotificationBlockedUser = false;
$wgSlackNotificationAddedArticle = true;
$wgSlackNotificationRemovedArticle = false;
$wgSlackNotificationMovedArticle = false;
$wgSlackNotificationEditedArticle = false;
$wgSlackNotificationFileUpload = false;

**Comment by kulttuuri** [comment] 2016-03-05 08:06
Can you try moving notification settings above the require_once statement
instead below was what I meant? So like:

$wgSlackNotificationBlockedUser = "false";
$wgSlackNotificationAddedArticle = "true";
require_once(...);

lauantai 5. maaliskuuta 2016 dedvardsson <notifications@github.com>
kirjoitti:

> Hi,
>
> Thanks for your reply.
> I have actually already added the require_once statement in my
> LocalSettings.php.
> The extension works, but the configuration of the notifications dosent
> seem to work.
>
> I have added my settings in LocalSettings.php below.
>
> require_once "$IP/extensions/SlackNotifications/slack_notifications.php";
>
> #SlackIntegration
> $wgSlackIncomingWebhookUrl = "
> https://hooks.slack.com/services/XXXXX/XXXXXXXXXXXXXXXXXXXXXXX";
> $wgSlackFromName = "Wiki";
> $wgWikiUrl = "http://192.168.60.130";
> $wgWikiUrlEnding = "/index.php/";
> $wgSlackSendMethod = "curl";
> $wgSlackNotificationNewUser = "false";
> $wgSlackNotificationBlockedUser = "false";
> $wgSlackNotificationAddedArticle = "true";
> $wgSlackNotificationRemovedArticle = "false";
> $wgSlackNotificationMovedArticle = "false";
> $wgSlackNotificationEditedArticle = "false";
> $wgSlackNotificationFileUpload = "false";
>
> I also tried:
> require_once "$IP/extensions/SlackNotifications/slack_notifications.php";
>
> #SlackIntegration
> $wgSlackIncomingWebhookUrl = "
> https://hooks.slack.com/services/XXXXX/XXXXXXXXXXXXXXXXXXXXXXX";
> $wgSlackFromName = "Wiki";
> $wgWikiUrl = "http://192.168.60.130";
> $wgWikiUrlEnding = "/index.php/";
> $wgSlackSendMethod = "curl";
> $wgSlackNotificationNewUser = false;
> $wgSlackNotificationBlockedUser = false;
> $wgSlackNotificationAddedArticle = true;
> $wgSlackNotificationRemovedArticle = false;
> $wgSlackNotificationMovedArticle = false;
> $wgSlackNotificationEditedArticle = false;
> $wgSlackNotificationFileUpload = false;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kulttuuri/slack_mediawiki/issues/2#issuecomment-192541997>
> .
>


-- 

Sent from my Iphone. Misspellings are subject to my mobile device =)

**Comment by dedvardsson** [comment] 2016-03-05 10:56
Hi, 
I tested to modify LocalSettings.php as you recomended, but i still can´t get the extension to not update on anything else then new articles. 

Here is my current LocalSettings

$wgSlackNotificationNewUser = "false";
$wgSlackNotificationBlockedUser = "false";
$wgSlackNotificationAddedArticle = "true";
$wgSlackNotificationRemovedArticle = "false";
$wgSlackNotificationMovedArticle = "false";
$wgSlackNotificationEditedArticle = "false";
$wgSlackNotificationFileUpload = "false";

require_once "$IP/extensions/SlackNotifications/slack_notifications.php";

$wgSlackIncomingWebhookUrl = "https://hooks.slack.com/services/XXXXXXX/XXXXXX/XXXXXXXXXXXXXXXxx";
$SlackFromName = "Wiki";
$wgWikiUrl = "http://192.168.60.130";
$wgWikiUrlEnding = "/index.php/";
$wgSlackSendMethod = "curl";

**Comment by kulttuuri** [comment] 2016-03-05 11:46
I think I know what the problem is. default_config.php with default variables always looks to be overriding custom variables. I'm on a train with battery running out but I'll dig into this once I'm home.

One fix could be to wrap all those variables inside isset function, like this: if (!isset($wgSlackNotificationNewUser)) $wgSlackNotificationNewUser = true;

Another fix would be to just wrap the if statements as first thing in the actual functions. Second way is probably better as you could add those variables after requiring the file, as that's more expected way to do it.

Also sorry for me mistakenly using strings in those variables, it should be booleans, so not "false" but false :)

**Comment by kulttuuri** [comment] 2016-03-06 19:56
Ok! I just pushed out commit that should have this fixed. I did some testing and things seemed to work now. Can you let me know if that fixed the problem? :)

**Comment by kulttuuri** [comment] 2016-03-06 19:57
And the format should be like this:

require_once "$IP/extensions/SlackNotifications/slack_notifications.php";
...
$wgSlackNotificationNewUser = false;
$wgSlackNotificationBlockedUser = false;
$wgSlackNotificationAddedArticle = true;
$wgSlackNotificationRemovedArticle = false;
$wgSlackNotificationMovedArticle = false;
$wgSlackNotificationEditedArticle = false;
$wgSlackNotificationFileUpload = false;

**Comment by dedvardsson** [comment] 2016-03-07 08:45
Hi Kulttuuri,
Thank you for this. 
Will be able to test in a couple of hours.

**Comment by dedvardsson** [comment] 2016-03-07 16:06
Hi Kultuuri, 

Thanks for the update. 
Works like a charm. 
Thank you very much. 
Another question, do you know if it´s possible to remove "edit|delete|history" from the slack notification? 

If i create an article in mediawiki for the moment this will be the post on slack:
Username (block | groups | talk | contribs) has created article Creatingarticle (edit | delete | history) Summary: Created page with 'This Should be posted on slack'

It would be nice if it would be possible to only get: 
Username has created article Creatingarticle, Summary:  'This Should be posted on slack'

**Comment by kulttuuri** [comment] 2016-03-07 20:49
Sure! I'll try to dig into this tomorrow to add configuration parameter to turn those off.

**Comment by dedvardsson** [comment] 2016-03-08 08:20
Oh, Thanks!

**Comment by kulttuuri** [comment] 2016-03-13 19:20
Done! Update and you'll get two new configuration parameters. More information here: https://github.com/kulttuuri/slack_mediawiki#remove-additional-links-from-user-and-article-pages

Let me know that it works and I can close this issue then. Thanks!

**Comment by dedvardsson** [comment] 2016-03-13 22:51
Thank you.
I will download and test it.

----
David Edvardsson

**Comment by kulttuuri** [comment] 2016-03-16 09:21
Working? :)

**Comment by dedvardsson** [comment] 2016-03-16 09:25
Tested yesterday. 
Works perfectly! 
Thanks :)

----
David Edvardsson

**Comment by kulttuuri** [comment] 2016-03-16 09:25
Great! I'll close the issue :+1:

**Closed by kulttuuri** 2016-03-16 09:25 UTC

**Comment by dedvardsson** [comment] 2016-03-16 16:06
Thanks for all your help

----
David Edvardsson

**Comment by kulttuuri** [comment] 2016-03-17 08:17
No problem! Happy to help :)
